server:
  port: 8080
  connection-timeout: 60000
  servlet:
    context-path: /web
  compression:
      min-response-size: 2048
      enabled: true
  tomcat:
    max-threads: 1000
    max-connections: 20000
    uri-encoding: utf-8

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.10.246:3306/csp_db?useUnicode=true&characterEncoding=utf8
      username: root
      password: fxzx123